default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  host: localhost
  pool: 5

development:
  <<: *default
  database: api_certs_development

test:
  <<: *default
  database: api_certs_test

production:
  url: <%= ENV['DATABASE_URL'] %>

